apiVersion: apps/v1
kind: Deployment
metadata:
  name: invalid-image-tag
  namespace: cloudops-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invalid-image-tag
  template:
    metadata:
      labels:
        app: invalid-image-tag
    spec:
      containers:
        - name: app
          image: nginx:this-tag-does-not-exist-cloudops
